const fs = require("fs");
const path = require("path");
const admin = require("firebase-admin");
const KuroshiroModule = require("kuroshiro");
const AnalyzerModule = require("kuroshiro-analyzer-kuromoji");

const Kuroshiro = KuroshiroModule.default || KuroshiroModule;
const KuromojiAnalyzer = AnalyzerModule.default || AnalyzerModule;

const ROOT = process.env.GITHUB_WORKSPACE || path.resolve(__dirname, "..");
const OUTPUT = path.join(ROOT, "public", "card_readings_20261005.js");
const REPORT = path.join(ROOT, "tools", "card_readings_report_20261005.json");
const VERSION = "20261005_readings1";

const COLLECTIONS = [
  "cards",
  "support_cards",
  "supports",
  "supportCards",
  "ex_support_cards",
  "ex_supports",
  "exSupportCards",
  "ex_support",
];

function normalizeKana(value) {
  return String(value || "")
    .normalize("NFKC")
    .trim()
    .toLowerCase()
    .replace(/[ァ-ヶ]/g, (ch) => String.fromCharCode(ch.charCodeAt(0) - 0x60))
    .replace(/[\s　・･._-]+/g, "");
}

function explicitReading(data = {}) {
  const candidates = [
    data.ruby,
    data.reading,
    data.kana,
    data.searchKana,
    data.yomi,
    data.furigana,
  ];
  return candidates.find((value) => String(value || "").trim()) || "";
}

function parseStaticCards(fileName) {
  const file = path.join(ROOT, "public", fileName);
  if (!fs.existsSync(file)) return [];
  const text = fs.readFileSync(file, "utf8");
  const out = [];
  const re = /\b(?:card|unit|support)\(\s*["']([^"']+)["']\s*,\s*["']([^"']+)["']/g;
  let match;
  while ((match = re.exec(text))) {
    out.push({
      id: String(match[1] || "").trim(),
      name: String(match[2] || "").trim(),
      source: `static:${fileName}`,
      reading: "",
    });
  }
  return out;
}

async function main() {
  const rawSecret = process.env.FIREBASE_SERVICE_ACCOUNT_JSON;
  if (!rawSecret) throw new Error("FIREBASE_SERVICE_ACCOUNT_JSON is missing");
  const serviceAccount = JSON.parse(rawSecret);

  admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
    projectId: serviceAccount.project_id || "tcg-0bato",
  });
  const db = admin.firestore();

  const cards = new Map();

  for (const collectionName of COLLECTIONS) {
    try {
      const snapshot = await db.collection(collectionName).get();
      snapshot.forEach((doc) => {
        const data = doc.data() || {};
        const id = String(data.id || doc.id || "").trim();
        const name = String(data.name || "").trim();
        if (!id || !name) return;
        cards.set(id, {
          id,
          name,
          source: `firestore:${collectionName}`,
          reading: explicitReading(data),
        });
      });
      console.log(`[readings] ${collectionName}: ${snapshot.size}`);
    } catch (error) {
      console.warn(`[readings] skip ${collectionName}:`, error?.message || error);
    }
  }

  for (const fileName of [
    "starter_support_cards.js",
    "fairy_tale_cards.js",
    "jewel_cards.js",
  ]) {
    for (const card of parseStaticCards(fileName)) {
      if (!cards.has(card.id)) cards.set(card.id, card);
    }
  }

  const kuroshiro = new Kuroshiro();
  await kuroshiro.init(new KuromojiAnalyzer());

  const entries = [];
  const unresolved = [];
  let explicitCount = 0;
  let generatedCount = 0;

  for (const card of [...cards.values()].sort((a, b) => a.id.localeCompare(b.id, "ja"))) {
    let reading = normalizeKana(card.reading);
    let method = "explicit";
    if (reading) {
      explicitCount += 1;
    } else {
      try {
        reading = normalizeKana(
          await kuroshiro.convert(card.name, {
            to: "hiragana",
            mode: "normal",
            romajiSystem: "hepburn",
          }),
        );
      } catch (error) {
        console.warn(`[readings] convert failed: ${card.id} ${card.name}`, error?.message || error);
      }
      method = "kuroshiro";
      if (reading) generatedCount += 1;
    }

    if (!reading) {
      reading = normalizeKana(card.name);
      method = "fallback-name";
      unresolved.push({ id: card.id, name: card.name, source: card.source });
    }

    entries.push({
      id: card.id,
      name: card.name,
      reading,
      source: card.source,
      method,
    });
  }

  const compactEntries = entries.map(({ id, name, reading }) => [id, name, reading]);
  const output = `// Auto-generated by tools/generate_card_readings.cjs.\n` +
`// Do not hand-edit; regenerate from Firestore/static card definitions.\n` +
`(() => {\n` +
`  "use strict";\n` +
`  const VERSION = ${JSON.stringify(VERSION)};\n` +
`  const ENTRIES = ${JSON.stringify(compactEntries, null, 2)};\n` +
`  const apiState = { installed: 0, attempts: 0 };\n` +
`  const expose = () => {\n` +
`    const byId = Object.fromEntries(ENTRIES.map(([id, name, reading]) => [id, { name, reading }]));\n` +
`    const byName = Object.fromEntries(ENTRIES.map(([id, name, reading]) => [name, { id, reading }]));\n` +
`    window.TCG_CARD_READINGS = { version: VERSION, count: ENTRIES.length, byId, byName };\n` +
`  };\n` +
`  const install = () => {\n` +
`    apiState.attempts += 1;\n` +
`    const api = window.TCG_KANA_SEARCH;\n` +
`    if (api && typeof api.add === "function") {\n` +
`      for (const [, name, reading] of ENTRIES) {\n` +
`        if (reading && name && api.add(reading, name)) apiState.installed += 1;\n` +
`      }\n` +
`      document.documentElement.dataset.cardReadings = VERSION;\n` +
`      window.dispatchEvent(new CustomEvent("tcg:card-readings-ready", {\n` +
`        detail: { version: VERSION, count: ENTRIES.length, installed: apiState.installed },\n` +
`      }));\n` +
`      return;\n` +
`    }\n` +
`    if (apiState.attempts < 240) setTimeout(install, 50);\n` +
`    else console.error("[card_readings] TCG_KANA_SEARCH was not ready");\n` +
`  };\n` +
`  expose();\n` +
`  install();\n` +
`})();\n`;

  fs.writeFileSync(OUTPUT, output, "utf8");
  const report = {
    version: VERSION,
    generatedAt: new Date().toISOString(),
    total: entries.length,
    explicitCount,
    generatedCount,
    unresolvedCount: unresolved.length,
    unresolved,
    sources: Object.fromEntries(
      [...new Set(entries.map((x) => x.source))]
        .sort()
        .map((source) => [source, entries.filter((x) => x.source === source).length]),
    ),
  };
  fs.writeFileSync(REPORT, JSON.stringify(report, null, 2) + "\n", "utf8");

  console.log(`[readings] total=${report.total} explicit=${explicitCount} generated=${generatedCount} unresolved=${unresolved.length}`);
  if (!entries.length) throw new Error("No cards found; refusing to write an empty dictionary");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
